import type { Metadata } from "next";
import { LegalPage } from "../_components/SiteChrome";

export const metadata: Metadata = { title: "Datenschutz | CK Eventcenter" };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Rechtliches / 02" title="Datenschutz">
    <section><h2>1. Verantwortlicher</h2><p>CK Eventcenter<br />Inhaber: Cevat Demircan<br />Industriestraße 44a<br />59192 Bergkamen<br /><a href="mailto:info@ckeventcenter.de">info@ckeventcenter.de</a></p></section>
    <section><h2>2. Aufruf der Internetseite und Hosting</h2><p>Beim Aufruf der Internetseite verarbeiten die eingesetzten Hosting- und Auslieferungsdienste technisch erforderliche Verbindungsdaten. Dazu können insbesondere IP-Adresse, Zeitpunkt, aufgerufene Adresse, Referrer, Browser- und Geräteinformationen sowie Statuscodes gehören. Die Verarbeitung dient der sicheren, stabilen und schnellen Bereitstellung der Internetseite. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt im sicheren und störungsfreien Betrieb.</p><p>Die Internetseite wird über Netlify bereitgestellt und an eine Sites-/Cloudflare-Infrastruktur ausgeliefert. Soweit diese Anbieter Daten in unserem Auftrag verarbeiten, erfolgt dies auf Grundlage entsprechender Vereinbarungen zur Auftragsverarbeitung.</p></section>
    <section><h2>3. Hochzeitskonfigurator und Vorreservierungen</h2><p>Wenn Sie einen Hochzeitstermin vorreservieren, verarbeiten wir Name, E-Mail-Adresse, optional Telefonnummer, gewünschten Saal, Hochzeitsdatum, Gästezahl, ausgewählte Leistungen, Hinweise, Preisschätzung und eine Buchungsnummer. Die Verarbeitung ist erforderlich, um Ihre Anfrage zu bearbeiten, die Verfügbarkeit zu sichern und vorvertragliche Maßnahmen durchzuführen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.</p><p>Die Vorreservierung bleibt gespeichert, bis sie durch uns bestätigt, blockiert oder manuell freigegeben wird. Die zugehörige Anfrage bleibt gespeichert, solange sie für die Bearbeitung, Dokumentation oder gesetzliche Aufbewahrungspflichten erforderlich ist. Danach wird sie gelöscht.</p></section>
    <section><h2>4. Beratungstermin über Calendly</h2><p>Nach erfolgreicher Vorreservierung können Sie freiwillig einen Beratungstermin über Calendly buchen. Erst dann wird der Calendly-Kalender eingebettet. Dabei werden Name, E-Mail-Adresse und Buchungsnummer an Calendly übergeben, damit der Termin Ihrer Anfrage zugeordnet werden kann. Anbieter ist Calendly LLC. Calendly kann dabei eigene Cookies oder ähnliche Technologien einsetzen und Daten auch außerhalb der Europäischen Union verarbeiten. Es gelten ergänzend die im Kalender angezeigten Datenschutzhinweise von Calendly. Rechtsgrundlage für die von Ihnen gewünschte Terminvereinbarung ist Art. 6 Abs. 1 lit. b DSGVO; für nicht technisch erforderliche Speicherzugriffe gelten die Einwilligungsanforderungen des § 25 TDDDG.</p></section>
    <section><h2>5. Kontaktaufnahme</h2><p>Bei einer Kontaktaufnahme per E-Mail oder über die auf der Internetseite angebotenen Kontaktwege verarbeiten wir Ihre Angaben zur Bearbeitung der Nachricht. Je nach Inhalt erfolgt dies auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO oder unseres berechtigten Interesses an der Beantwortung allgemeiner Anfragen gemäß Art. 6 Abs. 1 lit. f DSGVO.</p></section>
    <section><h2>6. Externe Medien und technische Dienste</h2><p>Einzelne Bilder werden über die Infrastruktur von Wix ausgeliefert. Beim Laden wird technisch bedingt Ihre IP-Adresse an den jeweiligen Anbieter übertragen. In der geschützten Verwaltung werden außerdem Google Fonts geladen. Diese Bereiche sind nicht für allgemeine Besucher bestimmt.</p><p>Sofern die optionale Pracht-Control-Anbindung aktiviert ist, werden technische Ereignisse wie Seitenaufruf, Kontaktklick oder Formularabsendung an den konfigurierten Kontrolldienst übermittelt. Formularinhalte werden dabei nicht übertragen. Die Verarbeitung dient der Betriebsüberwachung und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p></section>
    <section><h2>7. Erforderliche Sitzungen</h2><p>Die geschützten Verwaltungsbereiche verwenden ausschließlich technisch erforderliche Sitzungscookies. Sie dienen der Anmeldung und Zugriffskontrolle, sind nicht für Werbezwecke bestimmt und laufen automatisch ab. Rechtsgrundlagen sind § 25 Abs. 2 Nr. 2 TDDDG und Art. 6 Abs. 1 lit. f DSGVO.</p></section>
    <section><h2>8. Empfänger und Drittlandübermittlungen</h2><p>Personenbezogene Daten erhalten nur Stellen, die sie für die genannten Zwecke benötigen. Dazu können Hosting-, Infrastruktur- und Terminbuchungsdienstleister gehören. Soweit eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums stattfindet, achten wir auf die Voraussetzungen der Art. 44 ff. DSGVO, beispielsweise einen Angemessenheitsbeschluss oder geeignete Garantien.</p></section>
    <section><h2>9. Ihre Rechte</h2><p>Sie haben im Rahmen der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Außerdem können Sie sich bei einer Datenschutzaufsichtsbehörde beschweren.</p></section>
    <section><h2>10. Sicherheit und Aktualität</h2><p>Wir treffen angemessene technische und organisatorische Maßnahmen zum Schutz Ihrer Daten. Diese Datenschutzerklärung wird angepasst, wenn sich die eingesetzten Dienste oder rechtlichen Anforderungen ändern.</p><p>Stand: August 2026</p></section>
  </LegalPage>;
}
